# Handling Imbalanced with Machine Learning

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [10]:
X = df.drop(columns = ['Class'])

In [11]:
y = df['Class']

In [12]:
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [13]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [33]:
###Crossvalidation and Hyperparameter Tuning

In [14]:
from sklearn.linear_model import LogisticRegression

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold, GridSearchCV

In [19]:
{'C': 10.0*np.arange(-2,3)}

{'C': array([-20., -10.,   0.,  10.,  20.])}

In [20]:
classifier = LogisticRegression()
grid = {'C': 10.0*np.arange(-2,3),
       'penalty': ['l1', 'l2']}
cv = KFold(n_splits = 5, shuffle = False)

In [27]:
clf = GridSearchCV(classifier, grid,cv =cv, n_jobs = -1, scoring = 'f1_macro')

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [29]:
clf.fit(X_train, y_train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan 0.83737868        nan 0.84072173]
  warnings.warn(
C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([-20., -10.,   0.,  10.,  20.]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [30]:
y_pred = clf.predict(X_test)

In [32]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56838    23]
 [   37    64]]
0.9989466661985184
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.74      0.63      0.68       101

    accuracy                           1.00     56962
   macro avg       0.87      0.82      0.84     56962
weighted avg       1.00      1.00      1.00     56962



In [34]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [35]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56856     5]
 [   21    80]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.94      0.79      0.86       101

    accuracy                           1.00     56962
   macro avg       0.97      0.90      0.93     56962
weighted avg       1.00      1.00      1.00     56962



# Under Sampling

In [36]:
##Under Sampling
## Reduce the points of Maximum Labels

In [38]:
y_train.value_counts()

0    227454
1       391
Name: Class, dtype: int64

In [39]:
from imblearn.under_sampling import NearMiss
from collections import Counter

In [45]:
ms = NearMiss(0.8)

In [47]:
X_train_ms, y_train_ms=ms.fit_resample(X_train, y_train)

In [48]:
X_train_ms.shape

(879, 30)

In [49]:
y_train_ms.shape

(879,)

In [51]:
print('The number of classes before fit{}'.format(Counter(y_train)))
print('The number of classes after fit{}'.format(Counter(y_train_ms)))

The number of classes before fitCounter({0: 227454, 1: 391})
The number of classes after fitCounter({0: 488, 1: 391})


In [52]:
0.8*488

390.40000000000003

In [53]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ms, y_train_ms)

RandomForestClassifier()

In [54]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[40116 16745]
 [    4    97]]
0.7059618693163864
              precision    recall  f1-score   support

           0       1.00      0.71      0.83     56861
           1       0.01      0.96      0.01       101

    accuracy                           0.71     56962
   macro avg       0.50      0.83      0.42     56962
weighted avg       1.00      0.71      0.83     56962



# Over Sampling

In [55]:
from imblearn.over_sampling import RandomOverSampler

In [58]:
os = RandomOverSampler(0.5)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print('The number of features before sampling {}'.format(Counter(y_train)))
print('The number of features after sampling {}'.format(Counter(y_train_os)))

The number of features before sampling Counter({0: 227454, 1: 391})
The number of features after sampling Counter({0: 227454, 1: 113727})


[[40116 16745]
 [    4    97]]
0.7059618693163864
              precision    recall  f1-score   support

           0       1.00      0.71      0.83     56861
           1       0.01      0.96      0.01       101

    accuracy                           0.71     56962
   macro avg       0.50      0.83      0.42     56962
weighted avg       1.00      0.71      0.83     56962



In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [61]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[56854     7]
 [   18    83]]
0.9995611109160493
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.92      0.82      0.87       101

    accuracy                           1.00     56962
   macro avg       0.96      0.91      0.93     56962
weighted avg       1.00      1.00      1.00     56962



# SMOTETomek

In [62]:
from imblearn.combine import SMOTETomek

In [65]:
os = SMOTETomek(0.75)
X_train_os, y_train_os = os.fit_resample(X_train, y_train)
print('The number of features before sampling is {}'.format(Counter(y_train)))
print('The number of features after sampling is {}'.format(Counter(y_train)))

C:\Users\hp\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(

KeyboardInterrupt



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)

In [ ]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Ensemble Techniques

In [67]:
from imblearn.ensemble import EasyEnsembleClassifier

In [69]:
easy = EasyEnsembleClassifier()
easy.fit(X_train, y_train)

EasyEnsembleClassifier()

In [70]:
y_pred = easy.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[54932     9]
 [ 1929    92]]
0.9659773182121414
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     56861
           1       0.05      0.91      0.09       101

    accuracy                           0.97     56962
   macro avg       0.52      0.94      0.53     56962
weighted avg       1.00      0.97      0.98     56962

